# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.2+2

environment:
  sdk: ">=3.4.3 <4.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # Cupertino style icons
  cupertino_icons: ^1.0.8
    # getx state management
  get: ^4.6.6

  #for api call
  http: ^1.3.0
  
  #csv to list 
  csv: ^6.0.0

  #for lottie files
  lottie: ^3.2.0

  # this is the actual database
  hive: ^2.2.3

  #this will help us to initialize data
  hive_flutter: ^1.1.0
  
  # for integrating ads
  google_mobile_ads: ^5.3.0

  firebase_core: ^3.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  change_app_package_name: ^1.3.0

  # Encourages good practices
  flutter_lints: ^4.0.0


flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/